version: '3'
 
volumes:
  # static volume will be mounted to both nginx and django gunicorn services.
  static_volume:
  # postgres data volume will be mounted to postgres services 
  postgres_data:
 
services:

  # sql:
  #   image: microsoft/mssql-server-linux
  #   environment:
  #     SA_PASSWORD: StrongPass123
  #     ACCEPT_EULA: Y
  #     MSSQL_PID: Developer
  #   ports:
  #     - "1433:1433"

#TO BACKUP POSTGRES RUN THIS SCRIPT TO DOWNLOAD IMAGE AND BACKUP IN THAT VOLUME
# docker run -it --name pgback -v /path/backup/host:/var/lib/postgresql/data --network composeNetwork postgres /bin/bash
#TO RESTORE RUN THIS SCRIPT
# docker start -a -i pgback
  postgres:
    command: postgres -c max_connections=100
    build:
      context: .
      # it points to the docker file which has instruction to build this service.
      dockerfile: ./docker/postgres/dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    # all environment variables are defined in below file.
    env_file:
      - ./docker/postgres/.postgres_local_env
 
  django:
    build:
      context: .
      # it points to the docker file which has instruction to build this service.
      dockerfile: ./docker/django/dockerfile
    # this command will execute after execution all build steps from './docker/django/dockerfile'
    command: /gunicorn.sh
    volumes:
      - .:/app
      - ./static:/vol/web/static
    # links attribute will let postgres service become available first.
    depends_on:
      - postgres
    expose:
      - "8000"
    restart: always
    env_file:
      - ./docker/django/.django_local_env

  nginx:
    hostname: osg-support.cops.com
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static:/vol/web/static
    links:
      - django
    restart: always
    env_file:
      - ./docker/django/.django_local_env