# Generated by Django 3.2.6 on 2021-11-08 18:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_sign', models.BooleanField(default=False)),
                ('valid', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('kind', models.CharField(max_length=10)),
                ('app_permission', models.ManyToManyField(to='core.AppPermission')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='core.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userrequest', to='core.userprofile')),
            ],
        ),
    ]
