# Generated by Django 3.2.6 on 2021-12-28 19:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile.png', upload_to=core.models.user_image_path, verbose_name='Image'),
        ),
    ]
