# Generated by Django 3.2.6 on 2021-11-12 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['status', '-open_date']},
        ),
    ]
