# Generated by Django 3.2.6 on 2021-11-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='messages',
            field=models.ManyToManyField(to='core.Message'),
        ),
    ]
