# Generated by Django 3.2.6 on 2021-11-01 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ticket_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
