# Generated by Django 3.2.6 on 2021-10-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211021_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=15)),
                ('ip', models.CharField(max_length=15)),
                ('switch_port', models.IntegerField(default=0)),
                ('vlan', models.IntegerField(default=0)),
                ('mac', models.CharField(max_length=17)),
                ('model', models.CharField(max_length=20)),
                ('serial_num', models.CharField(max_length=17)),
                ('role', models.CharField(max_length=30)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch')),
                ('connected_pc', models.ManyToManyField(to='core.PC')),
            ],
            options={
                'ordering': ['-ip'],
            },
        ),
    ]
