# Generated by Django 3.2.6 on 2021-12-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211222_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=10, verbose_name='Language'),
        ),
    ]
