# Generated by Django 3.2.6 on 2021-11-12 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ticket_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userrequest', to='core.category'),
        ),
        migrations.AddField(
            model_name='request',
            name='file_scan',
            field=models.FileField(blank=True, null=True, upload_to='requests/'),
        ),
    ]
