# Generated by Django 3.2.6 on 2021-11-12 22:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211113_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='file_scan',
            field=models.FileField(blank=True, null=True, upload_to=core.models.user_directory_path),
        ),
    ]
