# Generated by Django 3.2.6 on 2021-11-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_message_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='Open', max_length=10),
        ),
    ]
