# Generated by Django 3.2.6 on 2021-11-18 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dvr_fingerprint_firewall_switch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-status', 'open_date']},
        ),
    ]
