# Generated by Django 3.2.6 on 2021-11-18 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('-open_date', '-status')},
        ),
    ]
