# Generated by Django 3.2.6 on 2021-11-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-status', '-open_date']},
        ),
    ]
