# Generated by Django 3.2.6 on 2021-11-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-status']},
        ),
    ]
